/**
 * Canonical risk indicator library — single source of truth.
 * Imported by both IndicatorPicker.jsx and useRiskIndicators.js to avoid circular deps.
 */
export const ALL_INDICATORS = [
  { id: 'geo',        name: 'High-Risk Geography',               description: 'Operating in a high-risk or non-cooperative jurisdiction (FATF grey/blacklist)',      applies: ['NP_Client','ORG_Client','NP_Related_Party','ORG_Related_Party'], category: 'Geography & Sector',                sort_order: 0  },
  { id: 'sector',     name: 'High-Risk Sector / Industry',       description: 'Operating in a high-risk sector (e.g. crypto, gambling, arms, adult)',                 applies: ['NP_Client','ORG_Client','NP_Related_Party','ORG_Related_Party'], category: 'Geography & Sector',                sort_order: 1  },
  { id: 'cash',       name: 'Cash-Intensive Business',           description: 'Primary operations involve large cash volumes or cash-equivalent transactions',         applies: ['ORG_Client'],                                                    category: 'Geography & Sector',                sort_order: 2  },
  { id: 'pep',        name: 'PEP Status',                        description: 'Client or related party is a Politically Exposed Person',                              applies: ['NP_Client','NP_Related_Party'],                                   category: 'PEP & Sanctions',                   sort_order: 3  },
  { id: 'sanctions',  name: 'Sanctions / Adverse Media',         description: 'Confirmed or possible match on sanctions, PEP or adverse media lists',                 applies: ['NP_Client','ORG_Client','NP_Related_Party','ORG_Related_Party'], category: 'PEP & Sanctions',                   sort_order: 4  },
  { id: 'pep_rp',     name: 'Politically Exposed Related Party', description: 'A UBO, director, or key related party is a PEP',                                       applies: ['NP_Client','ORG_Client','NP_Related_Party','ORG_Related_Party'], category: 'PEP & Sanctions',                   sort_order: 5  },
  { id: 'ownership',  name: 'Complex Ownership Structure',       description: 'Multi-layered, opaque, or nominee-based ownership arrangements',                       applies: ['ORG_Client','ORG_Related_Party'],                                 category: 'Ownership & Structure',             sort_order: 6  },
  { id: 'opaque',     name: 'Opaque Ownership / Nominee',        description: 'Use of nominee shareholders, bearer shares, or trusts obscuring beneficial ownership', applies: ['ORG_Client','ORG_Related_Party'],                                 category: 'Ownership & Structure',             sort_order: 7  },
  { id: 'txn',        name: 'Unusual Transaction Pattern',       description: 'Transactions inconsistent with stated purpose, profile, or expected behaviour',        applies: ['NP_Client','ORG_Client','NP_Related_Party','ORG_Related_Party'], category: 'Transaction & Financial Behaviour', sort_order: 8  },
  { id: 'sof',        name: 'Inconsistent SoF/SoW',              description: 'Source of funds or wealth cannot be adequately explained or documented',               applies: ['NP_Client','ORG_Client','NP_Related_Party','ORG_Related_Party'], category: 'Transaction & Financial Behaviour', sort_order: 9  },
  { id: 'nftf',       name: 'Non-Face-to-Face Relationship',     description: 'Client relationship established without in-person verification',                       applies: ['NP_Client','ORG_Client','NP_Related_Party','ORG_Related_Party'], category: 'Relationship & Onboarding',         sort_order: 10 },
  { id: 'introducer', name: 'Third-Party Introducer',            description: 'Client was introduced by a third party whose identity or integrity is uncertain',       applies: ['NP_Client','ORG_Client','NP_Related_Party','ORG_Related_Party'], category: 'Relationship & Onboarding',         sort_order: 11 },
];